name: CI/CD for Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: 'jdk'
        check-latest: false
        server-id: github

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/spring-api:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DOCKER_SSH_KEY }}

    - name: Deploy to Docker server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.DOCKER_SSH_KEY }} user@${{ secrets.DOCKER_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/spring-api:latest
          docker stop spring-api || true
          docker rm spring-api || true
          docker run -d -p 8080:8080 --name spring-api ${{ secrets.DOCKER_USERNAME }}/spring-api:latest
        EOF
